name: Auto Versioning
on: 
  workflow_run:
    workflows: ["Codacy Security Scan"]
    types: [completed]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   
          fetch-depth: 0 

      - name: Git Version
        uses: codacy/git-version@2.2.0
        with:
          release-branch: master
          dev-branch: dev
          prefix: v
